[package]
name = "tui-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ratatui = "0.29.0"
tachyonfx = "0.16.0"
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
