[project]
name = "ex-marimo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "marimo[recommended]>=0.13.15",
    "mohtml>=0.1.10",
    "requests>=2.32.4",
]
